spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

elasticsearch:
  rest:
    url: http://${ELASTIC_HOST}:${ELASTIC_PORT}